"""Initial migration

Revision ID: a7f2fa5e8fe5
Revises: 
Create Date: 2025-03-20 13:41:24.938605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7f2fa5e8fe5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('created_crm_objects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('object_id', sa.String(length=255), nullable=False),
    sa.Column('object_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_created_crm_objects_object_id'), 'created_crm_objects', ['object_id'], unique=False)
    op.create_index(op.f('ix_created_crm_objects_object_type'), 'created_crm_objects', ['object_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_created_crm_objects_object_type'), table_name='created_crm_objects')
    op.drop_index(op.f('ix_created_crm_objects_object_id'), table_name='created_crm_objects')
    op.drop_table('created_crm_objects')
    # ### end Alembic commands ###
