services:
  db:
    image: postgres:14
    container_name: hubspot_crm_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init-test-db.sql:/docker-entrypoint-initdb.d/init-test-db.sql

  test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hubspot_crm_tests
    depends_on:
      - db
    environment:
      FLASK_ENV: testing
      RUN_TESTS: "1"
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      TEST_DB_NAME: ${TEST_DB_NAME}

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hubspot_crm_app
    depends_on:
      - db
    ports:
      - "5001:5001"
    environment:
      FLASK_ENV: production
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      RUN_TESTS: "0"
      HUBSPOT_CLIENT_ID: ${HUBSPOT_CLIENT_ID}
      HUBSPOT_CLIENT_SECRET: ${HUBSPOT_CLIENT_SECRET}
      HUBSPOT_REFRESH_TOKEN: ${HUBSPOT_REFRESH_TOKEN}

volumes:
  db_data:
